name: Auto-append daily log row

on:
  schedule:
    - cron: "5 13 * * *" # daily at ~09:05 America/New_York during EDT
  push:
    paths:
      - "daily/input.json"
      - "daily/config.json"
      - "scripts/update_daily_log.py"
      - "README.md"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Update Daily Log (auto-calc %)
        run: |
          python3 scripts/update_daily_log.py

      - name: Commit changes (if any)
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "Auto-update Daily Log"
            git push
          fi
